### ISSUE TITLE
ryd integration broken?

### ISSUE THREAD

**Issue by zaphod2010** [Yannik25/ha-ryd#8]
I noticed a few days ago that the ryd integration is not connecting any longer. I am always running the latest version of Home Assistant. So it's likely that the ryd backend changed - which would also explain why their app looks very much different

Error while setting up ryd platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryd/sensor.py", line 42, in setup_platform
    fetch()
  File "/config/custom_components/ryd/sensor.py", line 40, in fetch
    ryd_adapter.update()
  File "/config/custom_components/ryd/sensor.py", line 71, in update
    self.ryd.fetch()
  File "/usr/local/lib/python3.11/site-packages/pyryd/pyryd.py", line 101, in fetch
    ryd_auth_token = json_object["auth_token"]
                     ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'auth_token'

**Comment by CptKalibak** [comment]
Same here. 

My guess it has something to do with tt4.thinxcloud maybe they changed the host. I'm not sure though.

**Comment by voncaron** [comment]
Hello,

I just changed in pyryd.py from PyRyd:

`"{}/auth%2Flogin%2Flocal".format(self._ryd_api_server),`

to

`"{}/auth/login/local".format(self._ryd_api_server),`

and it is working again.

**Comment by Yannik25** [comment]
I released a new version to pypi and hacs, hopefully this issue is fixed.

**Comment by CustomRomClub** [comment]
Tried to use the latest version from HACS but i doesn't work anyways. Somebody an idea?

**Comment by voncaron** [comment]
Can you please post your config with anonymous login credentials.

**Comment by CustomRomClub** [comment]
Sure, here you are...

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: homeassistant-b05fb
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.246
  ip_ban_enabled: true
  login_attempts_threshold: 4

sensor:
 - platform: ryd
   url: https://tt4.thinxcloud.de
   email: !secret email
   password: !secret ryd

binary_sensor:
  - platform: ping
    scan_interval: 10
    name: marcel_display_status
    host: 192.168.0.34

  - platform: ping
    scan_interval: 10
    name: marcel_tv_status
    host: 192.168.0.24

command_line:
 - switch:
    name: 'marcel_tv'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/tv.php?=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/tv.php?value=off"
 - switch:
    name: 'marcel_display'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/pc_display.php?value=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/pc_display.php?value=off"
 - switch:
    name: 'vr_brille'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/marcel1.php?value=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/marcel1.php?value=off"
   
switch:
  - platform: template
    switches:
      marcel_display_active:
        value_template: "{{ is_state('binary_sensor.marcel_display_status', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.marcel_display
        turn_off:
          service: switch.turn_off
          entity_id: switch.marcel_display

      marcel_tv_active:
        value_template: "{{ is_state('binary_sensor.marcel_tv_status', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.marcel_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.marcel_tv

  - platform: wake_on_lan
    name: Marcel-PC
    host: 192.168.0.62
    mac: 2C:F0:5D:9F:15:C8
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: marcel-pc

sonoff:
  username: !secret email
  password: !secret sonoff

proxmoxve:
  - host: 192.168.0.249
    username: HomeAssistant
    password: !secret proxmox
    verify_ssl: false
    realm: pve
    nodes:
      - node: Proxmox
        containers:
          - 100
          - 101
          - 104
          - 105
        vms:
          - 103
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

**Comment by CustomRomClub** [comment]
`# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: homeassistant-b05fb
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.246
  ip_ban_enabled: true
  login_attempts_threshold: 4

sensor:
 - platform: ryd
   url: https://tt4.thinxcloud.de
   email: !secret email
   password: !secret ryd

binary_sensor:
  - platform: ping
    scan_interval: 10
    name: marcel_display_status
    host: 192.168.0.34

  - platform: ping
    scan_interval: 10
    name: marcel_tv_status
    host: 192.168.0.24

command_line:
 - switch:
    name: 'marcel_tv'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/tv.php?=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/tv.php?value=off"
 - switch:
    name: 'marcel_display'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/pc_display.php?value=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/pc_display.php?value=off"
 - switch:
    name: 'vr_brille'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/marcel1.php?value=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/marcel1.php?value=off"
   
switch:
  - platform: template
    switches:
      marcel_display_active:
        value_template: "{{ is_state('binary_sensor.marcel_display_status', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.marcel_display
        turn_off:
          service: switch.turn_off
          entity_id: switch.marcel_display

      marcel_tv_active:
        value_template: "{{ is_state('binary_sensor.marcel_tv_status', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.marcel_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.marcel_tv

  - platform: wake_on_lan
    name: Marcel-PC
    host: 192.168.0.62
    mac: 2C:F0:5D:9F:15:C8
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: marcel-pc

sonoff:
  username: !secret email
  password: !secret sonoff

proxmoxve:
  - host: 192.168.0.249
    username: HomeAssistant
    password: !secret proxmox
    verify_ssl: false
    realm: pve
    nodes:
      - node: Proxmox
        containers:
          - 100
          - 101
          - 104
          - 105
        vms:
          - 103
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key`

**Comment by CustomRomClub** [comment]
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: homeassistant-b05fb
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.246
  ip_ban_enabled: true
  login_attempts_threshold: 4

sensor:
 - platform: ryd
   url: https://tt4.thinxcloud.de
   email: !secret email
   password: !secret ryd

binary_sensor:
  - platform: ping
    scan_interval: 10
    name: marcel_display_status
    host: 192.168.0.34

  - platform: ping
    scan_interval: 10
    name: marcel_tv_status
    host: 192.168.0.24

command_line:
 - switch:
    name: 'marcel_tv'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/tv.php?=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/tv.php?value=off"
 - switch:
    name: 'marcel_display'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/pc_display.php?value=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/pc_display.php?value=off"
 - switch:
    name: 'vr_brille'
    command_on: "curl -X GET https://XXXXXXX@XXXXXXX.de/marcel1.php?value=on"
    command_off: "curl -X GET https://XXXXXXX@XXXXXXX.de/marcel1.php?value=off"
   
switch:
  - platform: template
    switches:
      marcel_display_active:
        value_template: "{{ is_state('binary_sensor.marcel_display_status', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.marcel_display
        turn_off:
          service: switch.turn_off
          entity_id: switch.marcel_display

      marcel_tv_active:
        value_template: "{{ is_state('binary_sensor.marcel_tv_status', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.marcel_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.marcel_tv

  - platform: wake_on_lan
    name: Marcel-PC
    host: 192.168.0.62
    mac: 2C:F0:5D:9F:15:C8
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: marcel-pc

sonoff:
  username: !secret email
  password: !secret sonoff

proxmoxve:
  - host: 192.168.0.249
    username: HomeAssistant
    password: !secret proxmox
    verify_ssl: false
    realm: pve
    nodes:
      - node: Proxmox
        containers:
          - 100
          - 101
          - 104
          - 105
        vms:
          - 103
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
```

**Comment by voncaron** [comment]
This looks okay

```
sensor:
 - platform: ryd
   url: https://tt4.thinxcloud.de
   email: !secret email
   password: !secret ryd
``` 

Can you please post the log file maybe more information there.

Joachim
